### ISSUE TITLE
BDD tesztek készítése

### ISSUE THREAD

**Issue by kalocsaadi** [BME-MIT-IET/iet-hf-2024-goon-squad#3]
Felelős: Czímer Bende

**Comment by bendi1119** [comment]
A dokumentáció váza és a tesztesetek specifikációja kész. A branch rebaselve lett az ( #1 során ) updatelt main-re, tehát mostmár Maven-en keresztül telepíthető a Cucumber és elkezdődhet az implementáció.

**Comment by bendi1119** [comment]
A Cucumber setupolása és a dokumentáció frissítése megtörtént.

**Comment by bendi1119** [comment]
A feature fájlok létrehozása és a dokumentáció frissítése megtörtént.

**Comment by bendi1119** [comment]
A lépésdefiníciók létrehozása, a tesztek futtatása és a dokumentáció véglegesítése megtörtént.

A feladat véleményem szerint készen van, mergelésre alkalmas.
